# Ingestion de données

In [28]:
import os
import pandas
import geopandas
from datetime import datetime

In [12]:
# lire le fichier geojson des stations
gdf = geopandas.read_file("../data/station_abidjan_v1.geojson")

In [21]:
# afficher les données
display(gdf)
display(gdf.sample())

,id,name,operator,shop,adresse,geometry
0,node/243778772,Station Service Shell Carrefour Duncan,Vivo Energy Côte d'Ivoire SA,None,Aghien;Cocody;Abidjan;Côte d'Ivoire,POINT (-3.99745 5.37826)
1,node/729781766,Station Service Pétro Ivoire,Pétro Ivoire SA,yes,Vieux Cocody;Cocody;Abidjan;Côte d'Ivoire,POINT (-4.00171 5.35252)
2,node/773848817,Station Service Pétro Ivoire Angré,Pétro Ivoire SA,None,Angré;Cocody;Abidjan;Côte d'Ivoire,POINT (-3.99095 5.40487)
3,node/773848861,Station Service Shell Angré,Vivo Energy Côte d'Ivoire SA,None,None,POINT (-3.99048 5.40473)
4,node/775786955,Corlay Riviera 3,Corlay Côte d'Ivoire SA,None,Riviera 3;Cocody;Abidjan;Côte d'Ivoire,POINT (-3.95992 5.35492)
...,...,...,...,...,...,...
318,node/11866244469,SIP,Société Ivoirienne de Pétrole,None,None,POINT (-4.00433 5.27852)
319,node/11904808382,Total,None,None,None,POINT (-3.96315 5.34249)
320,node/12059902041,Shell,None,None,None,POINT (-3.98735 5.38477)
321,node/12063738451,Afriquia,None,None,None,POINT (-3.86053 5.23127)
322,node/12122258220,Petro Ivoire,None,None,None,POINT (-3.94034 5.39732)

,id,name,operator,shop,adresse,geometry
298,node/10840041006,Station Shell,None,None,None,POINT (-4.00587 5.4117)

In [23]:
# exploitation 
gdf.describe()

,id,name,operator,shop,adresse,geometry
count,323,302,183,30,37,323
unique,323,161,28,4,15,323
top,node/12122258220,Shell,Vivo Energy Côte d'Ivoire SA,yes,Yopougon;Abidjan;Côte d’Ivoire,POINT (-3.990483 5.4047311)
freq,1,31,66,24,12,1

In [ ]:
# renommer les colonnes
gdf_clean = gdf.rename(columns={
    "name": "nom",
    "operator": "operateur",

})

display(gdf.columns) 
display(gdf_clean)

Index(['id', 'name', 'operator', 'shop', 'adresse', 'geometry'], dtype='object')

,id,nom,operateur,shop,adresse,geometry
0,node/243778772,Station Service Shell Carrefour Duncan,Vivo Energy Côte d'Ivoire SA,None,Aghien;Cocody;Abidjan;Côte d'Ivoire,POINT (-3.99745 5.37826)
1,node/729781766,Station Service Pétro Ivoire,Pétro Ivoire SA,yes,Vieux Cocody;Cocody;Abidjan;Côte d'Ivoire,POINT (-4.00171 5.35252)
2,node/773848817,Station Service Pétro Ivoire Angré,Pétro Ivoire SA,None,Angré;Cocody;Abidjan;Côte d'Ivoire,POINT (-3.99095 5.40487)
3,node/773848861,Station Service Shell Angré,Vivo Energy Côte d'Ivoire SA,None,None,POINT (-3.99048 5.40473)
4,node/775786955,Corlay Riviera 3,Corlay Côte d'Ivoire SA,None,Riviera 3;Cocody;Abidjan;Côte d'Ivoire,POINT (-3.95992 5.35492)
...,...,...,...,...,...,...
318,node/11866244469,SIP,Société Ivoirienne de Pétrole,None,None,POINT (-4.00433 5.27852)
319,node/11904808382,Total,None,None,None,POINT (-3.96315 5.34249)
320,node/12059902041,Shell,None,None,None,POINT (-3.98735 5.38477)
321,node/12063738451,Afriquia,None,None,None,POINT (-3.86053 5.23127)
322,node/12122258220,Petro Ivoire,None,None,None,POINT (-3.94034 5.39732)

In [30]:
#ajouter les colonnes villes_id et created_at
gdf_clean["ville_id"] = 1
gdf_clean["created_at"] = datetime.now()
display(gdf_clean.sample())

,id,nom,operateur,shop,adresse,geometry,ville_id,created_at
82,node/2899062488,Station Service Total Dokui,Total Côte d'Ivoire SA,None,None,POINT (-4.00629 5.40466),1,2025-03-26 21:20:08.579778

In [35]:
# nettoyer id et shop
gdf_clean["id"] = range(1,324)
gdf_clean["shop"] = gdf_clean["shop"].apply(
    lambda shop: True if shop=="yes" else False
)
display(gdf_clean.dtypes)
display(gdf_clean.sample())

id                     int64
nom                   object
operateur             object
shop                    bool
adresse               object
geometry            geometry
ville_id               int64
created_at    datetime64[us]
dtype: object

,id,nom,operateur,shop,adresse,geometry,ville_id,created_at
104,105,Station Service Corlay Plateau,Corlay Côte d'Ivoire SA,False,None,POINT (-4.02217 5.32434),1,2025-03-26 21:20:08.579778

In [37]:
# exporter gdf_clean
gdf_clean.to_file("../data/result/stations.shp")
gdf_clean.to_file("../data/result/stations.geojson")

C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyogrio\raw.py:723: RuntimeWarning: Field created_at create as date field, though DateTime requested.
  ogr_write(